- hosts: all
  roles:
    - fetch-python-sdist-output
  pre_tasks:
    - name: Rename whl files to branch specific name
      shell: "mv {{ item }}.*.whl {{ item }}-{{ zuul.branch | replace('/', '-') }}.whl"
      args:
        chdir: "src/{{ zuul.project.canonical_name }}/dist"
      with_items:
        - "skyline"
        - "skyline_apiserver"
        - "skyline_config"
        - "skyline_console"
        - "skyline_log"
        - "skyline_nginx"
        - "skyline_policy_manager"
    - name: Rename tar.gz files to branch specific name
      shell: "mv {{ item }}.*.tar.gz {{ item }}-{{ zuul.branch | replace('/', '-') }}.tar.gz"
      args:
        chdir: "src/{{ zuul.project.canonical_name }}/dist"
      with_items:
        - "skyline"
        - "skyline-apiserver"
        - "skyline-config"
        - "skyline-console"
        - "skyline-log"
        - "skyline-nginx"
        - "skyline-policy-manager"
