- hosts: all
  tasks:
    - name: Install tox, nvm, nodejs and yarn
      shell:
        executable: /bin/bash
        cmd: |
          # nvm
          wget -P $HOME --tries=10 --retry-connrefused --waitretry=60 --no-dns-cache --no-cache  https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh
          bash $HOME/install.sh
          . $HOME/.nvm/nvm.sh
          # nodejs
          NODE_VERSION=erbium
          nvm install --lts=$NODE_VERSION
          nvm alias default lts/$NODE_VERSION
          nvm use default
          # yarn
          npm install -g yarn
          # tox
          pip3 install tox
    - name: Build tarball and wheel
      shell:
        executable: /bin/bash
        cmd: |
          git submodule update --init
          . $HOME/.nvm/nvm.sh
          $HOME/.local/bin/tox -e package
      args:
        chdir: "src/{{ zuul.project.canonical_name }}"
    - name: Move all tar.gz and wheel packages into dist
      shell: "mv libs/{{ item }}/dist/* dist/"
      args:
        chdir: "src/{{ zuul.project.canonical_name }}"
      with_items:
        - "skyline-apiserver"
        - "skyline-config"
        - "skyline-console"
        - "skyline-log"
        - "skyline-nginx"
        - "skyline-policy-manager"

