- hosts: all
  tasks:
    - name: Build tarball and wheel
      shell:
        executable: /bin/bash
        cmd: |
          make install
          make package
      args:
        chdir: "src/{{ zuul.project.canonical_name }}"
