- hosts: all
  tasks:
    - name: Install tox
      shell:
        executable: /bin/bash
        cmd: |
          # tox
          pip3 install tox

    - name: Build tarball and wheel
      shell:
        executable: /bin/bash
        cmd: |
          $HOME/.local/bin/tox -e package
      args:
        chdir: "src/{{ zuul.project.canonical_name }}"

    - name: Rename whl files to branch specific name
      shell: "mv {{ item }}*.whl {{ item }}-{{ zuul.branch | replace('/', '-') }}.whl"
      args:
        chdir: "src/{{ zuul.project.canonical_name }}/dist"
      with_items:
        - "skyline_apiserver"

    - name: Rename tar.gz files to branch specific name
      shell: "mv {{ item }}*.tar.gz {{ item }}-{{ zuul.branch | replace('/', '-') }}.tar.gz"
      args:
        chdir: "src/{{ zuul.project.canonical_name }}/dist"
      with_items:
        - "skyline-apiserver"

