---
- job:
    name: skyline-functional-devstack
    parent: devstack
    description: |
      Skyline functional tests job based on devstack (single-node).
    pre-run: playbooks/devstack/pre.yaml
    run:
      - playbooks/devstack/run-devstack.yaml
      - playbooks/devstack/run-tox.yaml
    post-run:
      - playbooks/devstack/post.yaml
    required-projects:
      - skyline/skyline-apiserver
    vars:
      devstack_plugins:
        skyline-apiserver: https://opendev.org/skyline/skyline-apiserver
      zuul_copy_output:
        /var/log/skyline: logs
        /etc/skyline: logs
        /etc/nginx: logs
    host-vars:
      controller:
        tox_install_siblings: false
        tox_envlist: functional

- job:
    name: skyline-tox-unittest-py38
    parent: openstack-tox-py38
    description: |
      Skyline py38 unittest tests
    vars:
      python_version: 3.8
      tox_envlist: unittest-py38

- job:
    name: skyline-tox-lint-py38
    parent: openstack-tox-py38
    description: |
      Skyline code static analysis
    vars:
      python_version: 3.8
      tox_envlist: lint

- job:
    name: publish-skyline-python-branch-tarball
    parent: publish-openstack-artifacts
    description: |
            Publish the results tar.gz and whl packages to tarballs.openstack.org.
    pre-run: playbooks/python-tarball/pre.yaml
    run: playbooks/python-tarball/run.yaml
    vars:
      release_python: python3

- project:
    check:
      jobs:
        - skyline-tox-unittest-py38
        - skyline-tox-lint-py38
        - skyline-functional-devstack
    gate:
      jobs:
        - skyline-tox-unittest-py38
        - skyline-tox-lint-py38
        - skyline-functional-devstack
    post:
      jobs:
        - publish-skyline-python-branch-tarball
